name: test-install-script

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test-install-script.yml'
      - 'wall_e_install.sh'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/test-install-script.yml'
      - 'wall_e_install.sh'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 22.04
            host_runner: ubuntu-latest
            package_manager: apt
            docker_image: ubuntu:22.04
          - name: Ubuntu 20.04
            host_runner: ubuntu-latest
            package_manager: apt
            docker_image: ubuntu:20.04
          - name: Arch Latest
            host_runner: ubuntu-latest
            package_manager: pacman
            docker_image: archlinux:latest


    name: ${{ matrix.name }}
    runs-on: ${{ matrix.host_runner }}
    container:
      image: ${{ matrix.docker_image }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ESP-IDF
        run: |
          bash wall_e_install.sh

  macos:
    strategy:
      matrix:
        include:
          - name: MacOS-latest
            host_runner: macos-latest
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.host_runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ESP-IDF
        run: |
          brew uninstall --ignore-dependencies python3
          brew cleanup --prune=1 -s
          sudo rm -rf /Library/Frameworks/Python.framework/Versions/
          brew install python@3.10
          bash wall_e_install.sh
