---
name: Test Build of Wall-E
on: [push, pull_request, workflow_dispatch]

jobs:
  build-test:
    name: Test Build of Wall-E
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.1
    strategy:
      matrix:
        test-apps: [1_led_matrix, 2_LSA, 3_MPU, 4_PWM, 5_line_following, 6_self_balancing]
    steps:
      - name: Force Install GIT latest
        run: |
          apt-get update \
          && DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common \
          && apt-get update \
          && add-apt-repository -y ppa:git-core/ppa \
          && apt-get update \
          && DEBIAN_FRONTEND=noninteractive apt-get install -y git
      - name: Setup Github Actions
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Test ${{ matrix.test-apps }}
        run: |
          . $IDF_PATH/export.sh
          cd ${{ matrix.test-apps }}
          idf.py build
